client:
  build: ./client
  volumes:
    - ./client/dist:/usr/share/nginx/html
  ports:
    - 9090:80
database:
  build: ./database
  ports:
      - 5432:5432
compilator:
  build: ./compilator
  volumes:
    - ./client:/root/project
